# Generated by Django 6.1.1 on 2026-10-04 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("started_count", models.BigIntegerField(default=0)),
                ("completed_count", models.BigIntegerField(default=0)),
                ("abandoned_count", models.BigIntegerField(default=0)),
                ("sum_duration_seconds", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat",
                        to="surveys.surveyversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FieldAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("field_id", models.UUIDField()),
                ("bucket", models.CharField(blank=True, max_length=128, null=True)),
                ("eligible_count", models.BigIntegerField(default=0)),
                ("answered_count", models.BigIntegerField(default=0)),
                ("sum_numeric", models.DecimalField(decimal_places=4, default=0, max_digits=24)),
                (
                    "min_numeric",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "max_numeric",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregates",
                        to="surveys.surveyversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["survey_version", "field_id"], name="analytics_f_survey__41d8e8_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("survey_version", "field_id", "bucket"),
                        name="uniq_field_aggregate",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
