# Generated by Django 6.1.1 on 2026-10-04 15:37

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("editor", "Editor"),
                            ("analyst", "Analyst"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access",
                        to="surveys.survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="survey",
            name="members",
            field=models.ManyToManyField(
                related_name="accessible_surveys",
                through="surveys.SurveyAccess",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SurveyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("schema", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["survey", "version_number"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("content", models.JSONField(blank=True, default=dict)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="surveys.surveyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "key"],
            },
        ),
        migrations.AddIndex(
            model_name="surveyaccess",
            index=models.Index(fields=["user", "survey"], name="surveys_sur_user_id_5b7ab4_idx"),
        ),
        migrations.AddConstraint(
            model_name="surveyaccess",
            constraint=models.UniqueConstraint(
                fields=("user", "survey"), name="uniq_survey_access"
            ),
        ),
        migrations.AddConstraint(
            model_name="survey",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="uniq_survey_slug_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyversion",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["schema"], name="surveyversion_schema_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyversion",
            constraint=models.UniqueConstraint(
                fields=("survey", "version_number"), name="uniq_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("survey",),
                name="one_draft_per_survey",
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("version", "key"), name="uniq_section_key_per_version"
            ),
        ),
    ]
