/**
 * Parity with the backend evaluator.
 *
 * parity-fixtures.json is generated by running the REAL Python evaluator
 * (`surveys/logic.py`) over a schema that exercises cross-section
 * dependencies, conditional requiredness, option filtering and the
 * ghost-dependency case. These tests assert the TypeScript mirror reaches
 * identical conclusions.
 *
 * This matters more than it looks. The client evaluates locally so the form
 * responds instantly, but the server decides what is actually stored. If the
 * two ever disagree, a respondent answers a field the server considers
 * hidden and the answer is silently discarded.
 */

import { describe, expect, it } from "vitest";

import fixtures from "@/test/parity-fixtures.json";
import {
  isAnswered,
  missingRequired,
  pruneHidden,
  resolveRequired,
  resolveVisibility,
  visibleOptions,
  visibleSections,
} from "./logic";
import type { Answers, SurveySchema } from "./types";

const schema = fixtures.schema as unknown as SurveySchema;

describe("parity with the Python evaluator", () => {
  for (const testCase of fixtures.cases) {
    it(`resolves visibility identically: ${testCase.name}`, () => {
      const answers = testCase.answers as Answers;
      expect(resolveVisibility(schema, answers)).toEqual(testCase.visible);
    });

    it(`resolves requiredness identically: ${testCase.name}`, () => {
      const answers = testCase.answers as Answers;
      const visible = resolveVisibility(schema, answers);
      expect(resolveRequired(schema, answers, visible)).toEqual(testCase.required);
    });

    it(`filters options identically: ${testCase.name}`, () => {
      const answers = testCase.answers as Answers;
      const visible = resolveVisibility(schema, answers);

      for (const [fieldId, expected] of Object.entries(testCase.options)) {
        const field = schema.fields[fieldId];
        const got = visibleOptions(field, schema, answers, visible).map((o) => o.value);
        expect(got, `options for ${fieldId}`).toEqual(expected);
      }
    });
  }
});

describe("isAnswered", () => {
  it.each([
    [0, true],
    [false, true],
    ["no", true],
    [["a"], true],
    [null, false],
    ["", false],
    ["   ", false],
    [[], false],
  ])("treats %s as answered=%s", (value, expected) => {
    expect(isAnswered(value as never)).toBe(expected);
  });

  it("counts zero as an answer, which naive truthiness would discard", () => {
    expect(isAnswered(0)).toBe(true);
  });
});

describe("the ghost-dependency case", () => {
  it("drops a dependent field when its determining answer is hidden", () => {
    const country = Object.keys(schema.fields).find(
      (id) => schema.fields[id].key === "country",
    )!;
    const city = Object.keys(schema.fields).find((id) => schema.fields[id].key === "city")!;
    const district = Object.keys(schema.fields).find(
      (id) => schema.fields[id].key === "district",
    )!;

    // Answered Saudi Arabia, picked Riyadh, then switched to Egypt. The
    // stale Riyadh answer must not keep the district question alive.
    const visible = resolveVisibility(schema, { [country]: "eg", [city]: "riyadh" });

    expect(visible[city]).toBe(false);
    expect(visible[district]).toBe(false);
  });
});

describe("hidden fields are never required", () => {
  it("does not demand an answer the respondent cannot see", () => {
    const country = Object.keys(schema.fields).find(
      (id) => schema.fields[id].key === "country",
    )!;
    const city = Object.keys(schema.fields).find((id) => schema.fields[id].key === "city")!;
    const age = Object.keys(schema.fields).find((id) => schema.fields[id].key === "age")!;

    // City is required for over-21s, but Egypt hides the section it lives in.
    const answers = { [country]: "eg", [age]: 40 };
    const visible = resolveVisibility(schema, answers);

    expect(visible[city]).toBe(false);
    expect(resolveRequired(schema, answers, visible)[city]).toBe(false);
  });
});

describe("sections", () => {
  it("renders only sections with at least one visible field", () => {
    const country = Object.keys(schema.fields).find(
      (id) => schema.fields[id].key === "country",
    )!;

    const egypt = visibleSections(schema, resolveVisibility(schema, { [country]: "eg" }));
    const saudi = visibleSections(schema, resolveVisibility(schema, { [country]: "sa" }));

    expect(egypt.map((s) => s.key)).toEqual(["s1", "s3"]);
    expect(saudi.map((s) => s.key)).toEqual(["s1", "s2", "s3"]);
  });

  it("keeps a display-only section, since static content is a field", () => {
    const sections = visibleSections(schema, resolveVisibility(schema, {}));
    expect(sections.map((s) => s.key)).toContain("s3");
  });
});

describe("helpers", () => {
  it("reports which required fields are still outstanding", () => {
    const country = Object.keys(schema.fields).find(
      (id) => schema.fields[id].key === "country",
    )!;
    const visible = resolveVisibility(schema, {});
    const required = resolveRequired(schema, {}, visible);

    expect(missingRequired([country], {}, visible, required)).toEqual([country]);
  });

  it("does not report an answered required field", () => {
    const country = Object.keys(schema.fields).find(
      (id) => schema.fields[id].key === "country",
    )!;
    const answers = { [country]: "sa" };
    const visible = resolveVisibility(schema, answers);
    const required = resolveRequired(schema, answers, visible);

    expect(missingRequired([country], answers, visible, required)).toEqual([]);
  });

  it("prunes answers to hidden fields, as submit does server-side", () => {
    expect(pruneHidden({ a: 1, b: 2 }, { a: true, b: false })).toEqual({ a: 1 });
  });
});
